export const trendingNFTs = [
  {
    rank: 1,
    collection: "CryptoPunks",
    icon: "https://example.com/cryptopunks-icon.png",
    floorPrice: "120 ETH",
    volume: "1,200 ETH",
  },
  {
    rank: 2,
    collection: "Bored Ape Yacht Club",
    icon: "https://example.com/bayc-icon.png",
    floorPrice: "95 ETH",
    volume: "1,000 ETH",
  },
  {
    rank: 3,
    collection: "Azuki",
    icon: "https://example.com/azuki-icon.png",
    floorPrice: "15 ETH",
    volume: "850 ETH",
  },
  {
    rank: 4,
    collection: "Mutant Ape Yacht Club",
    icon: "https://example.com/mayc-icon.png",
    floorPrice: "17 ETH",
    volume: "700 ETH",
  },
  {
    rank: 5,
    collection: "Doodles",
    icon: "https://example.com/doodles-icon.png",
    floorPrice: "10 ETH",
    volume: "600 ETH",
  },
  {
    rank: 6,
    collection: "Moonbirds",
    icon: "https://example.com/moonbirds-icon.png",
    floorPrice: "8 ETH",
    volume: "550 ETH",
  },
  {
    rank: 7,
    collection: "Clone X",
    icon: "https://example.com/clonex-icon.png",
    floorPrice: "12 ETH",
    volume: "500 ETH",
  },
  {
    rank: 8,
    collection: "The Sandbox",
    icon: "https://example.com/sandbox-icon.png",
    floorPrice: "3 ETH",
    volume: "450 ETH",
  },
  {
    rank: 9,
    collection: "Decentraland",
    icon: "https://example.com/decentraland-icon.png",
    floorPrice: "2.5 ETH",
    volume: "400 ETH",
  },
  {
    rank: 10,
    collection: "Art Blocks",
    icon: "https://example.com/artblocks-icon.png",
    floorPrice: "7 ETH",
    volume: "380 ETH",
  },
  {
    rank: 11,
    collection: "World of Women",
    icon: "https://example.com/wow-icon.png",
    floorPrice: "4 ETH",
    volume: "350 ETH",
  },
  {
    rank: 12,
    collection: "Cool Cats",
    icon: "https://example.com/coolcats-icon.png",
    floorPrice: "6 ETH",
    volume: "300 ETH",
  },
  {
    rank: 13,
    collection: "Pudgy Penguins",
    icon: "https://example.com/pudgypenguins-icon.png",
    floorPrice: "5 ETH",
    volume: "280 ETH",
  },
  {
    rank: 14,
    collection: "VeeFriends",
    icon: "https://example.com/veefriends-icon.png",
    floorPrice: "10 ETH",
    volume: "250 ETH",
  },
  {
    rank: 15,
    collection: "Meebits",
    icon: "https://example.com/meebits-icon.png",
    floorPrice: "2 ETH",
    volume: "200 ETH",
  },
  {
    rank: 16,
    collection: "CyberKongz",
    icon: "https://example.com/cyberkongz-icon.png",
    floorPrice: "4.5 ETH",
    volume: "180 ETH",
  },
  {
    rank: 17,
    collection: "KaijuKingz",
    icon: "https://example.com/kaijukingz-icon.png",
    floorPrice: "2.8 ETH",
    volume: "150 ETH",
  },
  {
    rank: 18,
    collection: "Alien Frens",
    icon: "https://example.com/alienfrens-icon.png",
    floorPrice: "1.5 ETH",
    volume: "120 ETH",
  },
  {
    rank: 19,
    collection: "Loot (for Adventurers)",
    icon: "https://example.com/loot-icon.png",
    floorPrice: "3 ETH",
    volume: "100 ETH",
  },
  {
    rank: 20,
    collection: "Wolf Game",
    icon: "https://example.com/wolfgame-icon.png",
    floorPrice: "1 ETH",
    volume: "80 ETH",
  },
];

console.log(trendingNFTs);
